//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServicesTest.ProveedoresWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proveedor", Namespace="http://schemas.datacontract.org/2004/07/WCFServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Proveedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruc {
            get {
                return this.RucField;
            }
            set {
                if ((object.ReferenceEquals(this.RucField, value) != true)) {
                    this.RucField = value;
                    this.RaisePropertyChanged("Ruc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/WCFServices.Errores")]
    [System.SerializableAttribute()]
    public partial class RepetidoException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProveedoresWS.IProveedores")]
    public interface IProveedores {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedores/CrearProveedor", ReplyAction="http://tempuri.org/IProveedores/CrearProveedorResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFServicesTest.ProveedoresWS.RepetidoException), Action="http://tempuri.org/IProveedores/CrearProveedorRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/WCFServices.Errores")]
        WCFServicesTest.ProveedoresWS.Proveedor CrearProveedor(WCFServicesTest.ProveedoresWS.Proveedor proveedorACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedores/CrearProveedor", ReplyAction="http://tempuri.org/IProveedores/CrearProveedorResponse")]
        System.Threading.Tasks.Task<WCFServicesTest.ProveedoresWS.Proveedor> CrearProveedorAsync(WCFServicesTest.ProveedoresWS.Proveedor proveedorACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedores/ObtenerProveedor", ReplyAction="http://tempuri.org/IProveedores/ObtenerProveedorResponse")]
        WCFServicesTest.ProveedoresWS.Proveedor ObtenerProveedor(string ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedores/ObtenerProveedor", ReplyAction="http://tempuri.org/IProveedores/ObtenerProveedorResponse")]
        System.Threading.Tasks.Task<WCFServicesTest.ProveedoresWS.Proveedor> ObtenerProveedorAsync(string ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedores/ModificarProveedor", ReplyAction="http://tempuri.org/IProveedores/ModificarProveedorResponse")]
        WCFServicesTest.ProveedoresWS.Proveedor ModificarProveedor(WCFServicesTest.ProveedoresWS.Proveedor proveedorAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedores/ModificarProveedor", ReplyAction="http://tempuri.org/IProveedores/ModificarProveedorResponse")]
        System.Threading.Tasks.Task<WCFServicesTest.ProveedoresWS.Proveedor> ModificarProveedorAsync(WCFServicesTest.ProveedoresWS.Proveedor proveedorAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedores/EliminarProveedor", ReplyAction="http://tempuri.org/IProveedores/EliminarProveedorResponse")]
        void EliminarProveedor(string ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedores/EliminarProveedor", ReplyAction="http://tempuri.org/IProveedores/EliminarProveedorResponse")]
        System.Threading.Tasks.Task EliminarProveedorAsync(string ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedores/ListarProveedores", ReplyAction="http://tempuri.org/IProveedores/ListarProveedoresResponse")]
        WCFServicesTest.ProveedoresWS.Proveedor[] ListarProveedores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedores/ListarProveedores", ReplyAction="http://tempuri.org/IProveedores/ListarProveedoresResponse")]
        System.Threading.Tasks.Task<WCFServicesTest.ProveedoresWS.Proveedor[]> ListarProveedoresAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProveedoresChannel : WCFServicesTest.ProveedoresWS.IProveedores, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProveedoresClient : System.ServiceModel.ClientBase<WCFServicesTest.ProveedoresWS.IProveedores>, WCFServicesTest.ProveedoresWS.IProveedores {
        
        public ProveedoresClient() {
        }
        
        public ProveedoresClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProveedoresClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProveedoresClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProveedoresClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFServicesTest.ProveedoresWS.Proveedor CrearProveedor(WCFServicesTest.ProveedoresWS.Proveedor proveedorACrear) {
            return base.Channel.CrearProveedor(proveedorACrear);
        }
        
        public System.Threading.Tasks.Task<WCFServicesTest.ProveedoresWS.Proveedor> CrearProveedorAsync(WCFServicesTest.ProveedoresWS.Proveedor proveedorACrear) {
            return base.Channel.CrearProveedorAsync(proveedorACrear);
        }
        
        public WCFServicesTest.ProveedoresWS.Proveedor ObtenerProveedor(string ruc) {
            return base.Channel.ObtenerProveedor(ruc);
        }
        
        public System.Threading.Tasks.Task<WCFServicesTest.ProveedoresWS.Proveedor> ObtenerProveedorAsync(string ruc) {
            return base.Channel.ObtenerProveedorAsync(ruc);
        }
        
        public WCFServicesTest.ProveedoresWS.Proveedor ModificarProveedor(WCFServicesTest.ProveedoresWS.Proveedor proveedorAModificar) {
            return base.Channel.ModificarProveedor(proveedorAModificar);
        }
        
        public System.Threading.Tasks.Task<WCFServicesTest.ProveedoresWS.Proveedor> ModificarProveedorAsync(WCFServicesTest.ProveedoresWS.Proveedor proveedorAModificar) {
            return base.Channel.ModificarProveedorAsync(proveedorAModificar);
        }
        
        public void EliminarProveedor(string ruc) {
            base.Channel.EliminarProveedor(ruc);
        }
        
        public System.Threading.Tasks.Task EliminarProveedorAsync(string ruc) {
            return base.Channel.EliminarProveedorAsync(ruc);
        }
        
        public WCFServicesTest.ProveedoresWS.Proveedor[] ListarProveedores() {
            return base.Channel.ListarProveedores();
        }
        
        public System.Threading.Tasks.Task<WCFServicesTest.ProveedoresWS.Proveedor[]> ListarProveedoresAsync() {
            return base.Channel.ListarProveedoresAsync();
        }
    }
}
